/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** System Health Check */
    get: {
      responses: {
        /** @description System status */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
      };
    };
  };
  "/auth/register": {
    /** Register */
    post: operations["register"];
  };
  "/auth/login": {
    /** Login */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Session created */
        200: {
          headers: {
            "Set-Cookie"?: string;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Invalid credentials */
        401: {
          content: {
            "application/problem+json": components["schemas"]["Problem"];
          };
        };
      };
    };
  };
  "/auth/logout": {
    /** Logout */
    post: {
      responses: {
        /** @description Session cleared */
        200: {
          content: never;
        };
        /** @description Not logged in */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/me": {
    /** Get Current User */
    get: {
      responses: {
        /** @description Current user details */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Not logged in */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/csrf": {
    /**
     * Get CSRF Token
     * @description Use this token in X-CSRF-Token header for unsafe requests
     */
    get: {
      responses: {
        /** @description Token generated */
        200: {
          content: {
            "application/json": components["schemas"]["CsrfResponse"];
          };
        };
      };
    };
  };
  "/uploads/presign": {
    /** Create Presigned Upload URL */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PresignRequest"];
        };
      };
      responses: {
        /** @description URL generated */
        200: {
          content: {
            "application/json": components["schemas"]["PresignResponse"];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          content: never;
        };
      };
    };
  };
  "/uploads/complete": {
    /** Confirm Upload */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UploadConfirmation"];
        };
      };
      responses: {
        /** @description Upload marked as complete */
        204: {
          content: never;
        };
        /** @description Validation failed */
        400: {
          content: never;
        };
      };
    };
  };
  "/recipes": {
    /** List Recipes */
    get: {
      parameters: {
        query?: {
          /** @description Pagination cursor */
          cursor?: string;
          /** @description Search query text */
          q?: string;
          limit?: number;
          restrictions?: components["schemas"]["DietaryRestriction"][];
        };
      };
      responses: {
        /** @description List of recipes */
        200: {
          content: {
            "application/json": components["schemas"]["RecipeList"];
          };
        };
      };
    };
    /** Create Recipe Manually */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RecipeCreate"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["Recipe"];
          };
        };
      };
    };
  };
  "/recipes/{id}": {
    /** Get Recipe Details */
    get: {
      parameters: {
        path: {
          id: components["schemas"]["Uuid"];
        };
      };
      responses: {
        /** @description Recipe details */
        200: {
          content: {
            "application/json": components["schemas"]["Recipe"];
          };
        };
        /** @description Not found */
        404: {
          content: never;
        };
      };
    };
    /** Update Recipe */
    patch: {
      parameters: {
        path: {
          id: components["schemas"]["Uuid"];
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RecipeCreate"];
        };
      };
      responses: {
        /** @description Updated */
        200: {
          content: {
            "application/json": components["schemas"]["Recipe"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: components["schemas"]["Uuid"];
      };
    };
  };
  "/recipes/{id}/ingredients": {
    /** Add Ingredient to Recipe */
    post: {
      parameters: {
        path: {
          id: components["schemas"]["Uuid"];
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["IngredientAdd"];
        };
      };
      responses: {
        /** @description Ingredient added */
        200: {
          content: {
            "application/json": components["schemas"]["Recipe"];
          };
        };
      };
    };
  };
  "/recipes/{id}/images": {
    /** Link Image to Recipe */
    post: {
      parameters: {
        path: {
          id: components["schemas"]["Uuid"];
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            uploadId: components["schemas"]["Uuid"];
          };
        };
      };
      responses: {
        /** @description Image linked */
        200: {
          content: never;
        };
      };
    };
  };
  "/recipes/{id}/ai/steps": {
    /** AI Generate Steps */
    post: {
      parameters: {
        path: {
          id: components["schemas"]["Uuid"];
        };
      };
      responses: {
        /** @description Recipe updated with AI steps */
        200: {
          content: {
            "text/event-stream": string;
            "application/json": components["schemas"]["Recipe"];
          };
        };
      };
    };
  };
  "/recipes/{id}/ai/nutrition": {
    /** AI Estimate Nutrition */
    post: {
      parameters: {
        path: {
          id: components["schemas"]["Uuid"];
        };
      };
      responses: {
        /** @description Nutrition estimated */
        200: {
          content: {
            "application/json": components["schemas"]["Recipe"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Format: uuid
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    Uuid: string;
    /**
     * Format: date-time
     * @example 2023-10-27T10:00:00Z
     */
    Timestamp: string;
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string;
      /** @example Validation Error */
      title: string;
      /** @example 422 */
      status: number;
      /** @example Password must be at least 8 characters. */
      detail?: string;
      /** Format: uri */
      instance?: string;
      /** @description Unique request ID for tracing */
      correlationId: string;
    };
    User: {
      id: components["schemas"]["Uuid"];
      /** Format: email */
      email: string;
      full_name: string;
      is_active: boolean;
    };
    LoginRequest: {
      /** Format: email */
      username: string;
      password: string;
    };
    CsrfResponse: {
      csrfToken: string;
    };
    PresignRequest: {
      filename: string;
      /** @enum {string} */
      contentType: "image/jpeg" | "image/png" | "image/webp";
      sizeBytes: number;
    };
    PresignResponse: {
      uploadId: components["schemas"]["Uuid"];
      /** Format: uri */
      uploadUrl: string;
      /** Format: uri */
      imageUrl: string;
      fields?: {
        [key: string]: string;
      };
    };
    UploadConfirmation: {
      uploadId: components["schemas"]["Uuid"];
    };
    /** @enum {string} */
    DietaryRestriction: "vegan" | "vegetarian" | "gluten_free" | "dairy_free" | "nut_free" | "keto" | "paleo";
    Recipe: {
      id: components["schemas"]["Uuid"];
      title: string;
      description?: string;
      ingredients: string[];
      instructions: string[];
      dietaryTags: components["schemas"]["DietaryRestriction"][];
      prepTimeMinutes?: number;
      cookTimeMinutes?: number;
      calories?: number;
      created_at: components["schemas"]["Timestamp"];
      /** Format: uri */
      imageUrl?: string | null;
    };
    RecipeList: {
      data: components["schemas"]["Recipe"][];
      /** @description Base64 encoded cursor for next page */
      nextCursor?: string | null;
      hasMore: boolean;
    };
    RecipeCreate: {
      title: string;
      description?: string;
      ingredients: string[];
      /** @description Raw text or steps */
      instruction_text: string;
      dietary_tags: components["schemas"]["DietaryRestriction"][];
    };
    IngredientAdd: {
      name: string;
      amount: string;
    };
    /** @enum {string} */
    HealthStatus: "ok" | "degraded" | "down";
    HealthResponse: {
      status: components["schemas"]["HealthStatus"];
      checks: {
        db?: components["schemas"]["HealthStatus"];
        storage?: components["schemas"]["HealthStatus"];
        ai?: components["schemas"]["HealthStatus"];
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Register */
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description User created */
      201: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Email already registered */
      400: {
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
